server:
  port: 666
spring:
  mvc:
    view:
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javaweb?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    password:
    database: 3
    timeout:
    jedis:
      pool:
        #最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        #最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        min-idle: 0
        max-wait: 20000
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: utf-8
      enabled: true
logging:
  level:
    com.example.demo.dao: debug
    root: debug

mybatis:
  mapper-locations: classpath:**/*.xml